REPORTING_API_CONTRACTS = {
    "red_flag_alert": {
        "label": "Red Flag Alert reporting subsystem",
        "variables": [
            {"name": "campaign", "type": "string", "required": True, "description": "External campaign identifier from the reporting system"},
            {"name": "period_start", "type": "date", "required": True, "description": "Inclusive reporting start date"},
            {"name": "period_end", "type": "date", "required": True, "description": "Inclusive reporting end date"},
            {"name": "clinic_group", "type": "string", "required": True, "description": "Clinic group or geography bucket"},
            {"name": "clinic", "type": "string", "required": True, "description": "Clinic identifier or clinic label from the source system"},
            {"name": "form_fills", "type": "integer", "required": True, "description": "Completed screening or monitoring form submissions"},
            {"name": "red_flags_total", "type": "integer", "required": True, "description": "Total red flags triggered"},
            {"name": "patient_video_views", "type": "integer", "required": True, "description": "Patient red-flag education video views"},
            {"name": "reports_emailed_to_doctors", "type": "integer", "required": True, "description": "Doctor email reports sent"},
            {"name": "form_shares", "type": "integer", "required": True, "description": "Forms shared by clinics or doctors"},
            {"name": "patient_scans", "type": "integer", "required": True, "description": "Patient QR or link scans"},
            {"name": "follow_ups_scheduled", "type": "integer", "required": True, "description": "Follow-up reminders scheduled"},
            {"name": "reminders_sent", "type": "integer", "required": True, "description": "Reminder messages sent"},
        ],
    },
    "in_clinic": {
        "label": "In-clinic reporting subsystem",
        "variables": [
            {"name": "campaign", "type": "string", "required": True, "description": "External campaign identifier from the reporting system"},
            {"name": "period_start", "type": "date", "required": True, "description": "Inclusive reporting start date"},
            {"name": "period_end", "type": "date", "required": True, "description": "Inclusive reporting end date"},
            {"name": "clinic_group", "type": "string", "required": True, "description": "Clinic group or geography bucket"},
            {"name": "clinic", "type": "string", "required": True, "description": "Clinic identifier from the source system"},
            {"name": "doctor", "type": "string", "required": False, "description": "Doctor identifier from the source system"},
            {"name": "field_rep", "type": "string", "required": False, "description": "Field rep identifier from the source system; may be blank"},
            {"name": "shares", "type": "integer", "required": True, "description": "Collateral shares completed"},
            {"name": "link_opens", "type": "integer", "required": True, "description": "Doctor link opens"},
            {"name": "pdf_reads_completed", "type": "integer", "required": True, "description": "PDF reads to the last page"},
            {"name": "video_views", "type": "integer", "required": True, "description": "Video views"},
            {"name": "video_completions", "type": "integer", "required": True, "description": "Video completions"},
            {"name": "pdf_downloads", "type": "integer", "required": True, "description": "PDF downloads"},
        ],
    },
    "patient_education": {
        "label": "Patient education reporting subsystem",
        "variables": [
            {"name": "campaign", "type": "string", "required": True, "description": "External campaign identifier from the reporting system"},
            {"name": "period_start", "type": "date", "required": True, "description": "Inclusive reporting start date"},
            {"name": "period_end", "type": "date", "required": True, "description": "Inclusive reporting end date"},
            {"name": "clinic_group", "type": "string", "required": True, "description": "Clinic group or geography bucket"},
            {"name": "clinic", "type": "string", "required": True, "description": "Clinic identifier or clinic label from the source system"},
            {"name": "video_views", "type": "integer", "required": True, "description": "Patient video views"},
            {"name": "video_completions", "type": "integer", "required": True, "description": "Patient video completions"},
            {"name": "cluster_shares", "type": "integer", "required": True, "description": "Video-cluster shares"},
            {"name": "patient_scans", "type": "integer", "required": True, "description": "Patient scans or opens"},
            {"name": "banner_clicks", "type": "integer", "required": True, "description": "Brand banner clicks by doctors or clinic staff"},
        ],
    },
}
