# Generated by Django 4.2.29 on 2026-03-17 11:03

import apps.accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('project_manager', 'Project manager'), ('support_agent', 'Support agent'), ('department_owner', 'Department owner'), ('brand_manager', 'Brand manager'), ('field_rep', 'Field representative'), ('clinic_staff', 'Clinic staff'), ('doctor', 'Doctor')], default='support_agent', max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
