# Generated by Django 4.2.29 on 2026-03-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedFlagSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('form_fills', models.PositiveIntegerField(default=0)),
                ('red_flags_total', models.PositiveIntegerField(default=0)),
                ('patient_video_views', models.PositiveIntegerField(default=0)),
                ('reports_emailed_to_doctors', models.PositiveIntegerField(default=0)),
                ('form_shares', models.PositiveIntegerField(default=0)),
                ('patient_scans', models.PositiveIntegerField(default=0)),
                ('follow_ups_scheduled', models.PositiveIntegerField(default=0)),
                ('reminders_sent', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinic')),
                ('clinic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinicgroup')),
            ],
            options={
                'ordering': ['-period_end', 'clinic__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientEducationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('video_views', models.PositiveIntegerField(default=0)),
                ('video_completions', models.PositiveIntegerField(default=0)),
                ('cluster_shares', models.PositiveIntegerField(default=0)),
                ('patient_scans', models.PositiveIntegerField(default=0)),
                ('banner_clicks', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinic')),
                ('clinic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinicgroup')),
            ],
            options={
                'ordering': ['-period_end', 'clinic__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InClinicSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('shares', models.PositiveIntegerField(default=0)),
                ('link_opens', models.PositiveIntegerField(default=0)),
                ('pdf_reads_completed', models.PositiveIntegerField(default=0)),
                ('video_views', models.PositiveIntegerField(default=0)),
                ('video_completions', models.PositiveIntegerField(default=0)),
                ('pdf_downloads', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinic')),
                ('clinic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinicgroup')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.doctor')),
                ('field_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', 'clinic__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalGrowthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('webinar_attendees', models.PositiveIntegerField(default=0)),
                ('certificate_completed', models.PositiveIntegerField(default=0)),
                ('onboarded_certificate_completed', models.PositiveIntegerField(default=0)),
                ('non_onboarded_certificate_completed', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_growth_snapshots', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('system_type', models.CharField(choices=[('red_flag_alert', 'Red flag alert'), ('patient_education', 'Patient education'), ('in_clinic', 'In-clinic')], max_length=24)),
                ('doctors_added', models.PositiveIntegerField(default=0)),
                ('clinics_added', models.PositiveIntegerField(default=0)),
                ('clinics_with_shares', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinic')),
                ('clinic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campaigns.clinicgroup')),
            ],
            options={
                'ordering': ['-period_end', 'clinic__name'],
                'abstract': False,
            },
        ),
    ]
