# Generated by Django 4.2.29 on 2026-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('clinic_staff', 'Clinic staff'), ('brand_manager', 'Brand manager'), ('field_rep', 'Field rep'), ('patient', 'Patient'), ('internal', 'Internal')], default='internal', max_length=24),
        ),
    ]
