# Generated by Django 4.2.29 on 2026-04-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_ticket_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('default_source_system', models.CharField(choices=[('customer_support', 'Customer support'), ('project_manager', 'Project management'), ('in_clinic', 'In-clinic'), ('red_flag_alert', 'Red flag alert'), ('patient_education', 'Patient education'), ('manual', 'Manual')], default='manual', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='ticketing.ticketcategory')),
                ('default_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_types', to='ticketing.department')),
            ],
            options={
                'verbose_name': 'Ticket type',
                'verbose_name_plural': 'Ticket types',
                'ordering': ['category__display_order', 'category__name', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.ticketcategory'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.tickettypedefinition'),
        ),
    ]
