# Generated by Django 4.2.29 on 2026-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_ticketcategory_tickettypedefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='external_ticket_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_ticket_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_ticket_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_ticket_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_ticket_url',
            field=models.URLField(blank=True),
        ),
    ]
