# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_ticket_external_ticket_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='external_ticket_error',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='external_ticket_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='external_ticket_status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='external_ticket_synced_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='external_ticket_url',
        ),
    ]
