# Generated by Django 4.2.29 on 2026-04-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_ticket_external_ticket_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='external_ticket_log',
            field=models.TextField(blank=True),
        ),
    ]
