# Generated by Django 4.2.29 on 2026-04-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_ticket_external_ticket_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='external_directory_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='department',
            name='external_directory_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='external_directory_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='department',
            name='external_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
