# Generated by Django 4.2.29 on 2026-04-08 10:58

import apps.ticketing.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_department_external_directory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=apps.ticketing.models.ticket_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'heic', 'svg', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'txt'])]),
        ),
    ]
