# Generated by Django 4.2.29 on 2026-04-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_ticket_is_escalated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('clinic_staff', 'Clinic staff'), ('brand_manager', 'Brand manager'), ('publisher', 'Publisher'), ('field_rep', 'Field rep'), ('patient', 'Patient'), ('internal', 'Internal')], default='internal', max_length=24),
        ),
        migrations.AlterField(
            model_name='ticketroutingevent',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('delegated', 'Delegated'), ('escalated', 'Escalated'), ('returned', 'Returned to sender'), ('status_changed', 'Status changed')], max_length=24),
        ),
    ]
