# Generated by Django 4.2.29 on 2026-04-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_alter_ticket_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('clinic_staff', 'Clinic staff'), ('brand_manager', 'Brand manager'), ('publisher', 'Publisher'), ('field_rep', 'Field rep'), ('patient', 'Patient'), ('student', 'Student'), ('expert', 'Expert'), ('internal', 'Internal')], default='internal', max_length=24),
        ),
    ]
