# Generated by Django 4.2.29 on 2026-05-06 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0012_alter_ticket_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialInstructionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reference', models.CharField(max_length=255, unique=True)),
                ('doctor_id', models.CharField(max_length=64)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('doctor_email', models.EmailField(blank=True, max_length=254)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('clinic_phone', models.CharField(blank=True, max_length=32)),
                ('campaign_uuid', models.CharField(blank=True, max_length=128)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('campaign_field_rep_id', models.CharField(blank=True, max_length=64)),
                ('campaign_field_rep_internal_id', models.PositiveIntegerField(blank=True, null=True)),
                ('campaign_field_rep_name', models.CharField(blank=True, max_length=255)),
                ('assigned_field_rep_id', models.CharField(blank=True, max_length=64)),
                ('assigned_field_rep_internal_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_field_rep_name', models.CharField(blank=True, max_length=255)),
                ('rfa_current_status', models.CharField(blank=True, max_length=120)),
                ('rfa_status_code', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, max_length=1000)),
                ('approve_url', models.URLField(blank=True, max_length=1000)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approve_response', models.JSONField(blank=True, default=dict)),
                ('approve_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_special_instruction_reviews', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_instruction_review', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
