# Generated by Codex on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticketing", "0014_department_recipient_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialinstructionreview",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specialinstructionreview",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_special_instruction_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
