# Generated by Django 4.2.29 on 2026-03-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('response_mode', models.CharField(choices=[('standardized', 'Standardized solution'), ('direct_ticket', 'Direct ticket')], default='standardized', max_length=24)),
                ('solution_title', models.CharField(blank=True, max_length=255)),
                ('solution_body', models.TextField(blank=True)),
                ('associated_pdf_url', models.URLField(blank=True)),
                ('associated_video_url', models.URLField(blank=True)),
                ('default_ticket_type', models.CharField(default='Customer support', max_length=120)),
                ('source_system', models.CharField(default='Customer support', max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible_to_doctors', models.BooleanField(default=True)),
                ('is_visible_to_clinic_staff', models.BooleanField(default=True)),
                ('is_visible_to_brand_managers', models.BooleanField(default=True)),
                ('is_visible_to_field_reps', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='support_center.supportcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportSuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Support super categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=24)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_company', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('free_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('solution_provided', 'Solution provided'), ('ticket_created', 'Ticket created')], default='ticket_created', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='campaigns.campaign')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='support_center.supportitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
