# Generated by Django 4.2.29 on 2026-03-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support_center', '0001_initial'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportitem',
            name='ticket_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_items', to='ticketing.department'),
        ),
        migrations.AddField(
            model_name='supportcategory',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='support_center.supportsupercategory'),
        ),
        migrations.AlterUniqueTogether(
            name='supportitem',
            unique_together={('category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='supportcategory',
            unique_together={('super_category', 'slug')},
        ),
    ]
