# Generated by Django 4.2.29 on 2026-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportitem',
            name='is_visible_to_patients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='knowledge_type',
            field=models.CharField(choices=[('faq', 'FAQ'), ('ticket_case', 'Ticket case')], default='faq', max_length=24),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='source_document',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='source_flow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='ticket_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
