# Generated by Django 4.2.29 on 2026-04-08 10:56

import apps.support_center.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0003_supportitem_is_visible_to_patients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='source_flow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='source_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='support_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='support_center.supportcategory'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to=apps.support_center.models.support_request_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('pending_pm_review', 'Pending PM review'), ('solution_provided', 'Solution provided'), ('ticket_created', 'Ticket created')], default='ticket_created', max_length=24),
        ),
    ]
