# Generated by Django 4.2.29 on 2026-04-09 11:15

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def backfill_support_pages(apps, schema_editor):
    SupportItem = apps.get_model('support_center', 'SupportItem')
    SupportPage = apps.get_model('support_center', 'SupportPage')
    SupportRequest = apps.get_model('support_center', 'SupportRequest')

    page_cache = {}
    for item in SupportItem.objects.select_related('category', 'category__super_category'):
        page_name = (item.category.name or '').strip()
        if not page_name:
            continue
        cache_key = (item.source_system or '', item.source_flow or '', page_name)
        if cache_key not in page_cache:
            slug = slugify("-".join(part for part in [item.source_system, item.source_flow, page_name] if part))[:220]
            page, _ = SupportPage.objects.get_or_create(
                slug=slug,
                defaults={
                    'name': page_name,
                    'source_system': item.source_system or '',
                    'source_flow': item.source_flow or '',
                    'display_order': item.display_order,
                    'is_active': True,
                },
            )
            page_cache[cache_key] = page.pk
        item.page_id = page_cache[cache_key]
        item.save(update_fields=['page'])

    for support_request in SupportRequest.objects.select_related('item__page', 'item__category__super_category', 'support_category__super_category'):
        if support_request.item_id:
            if support_request.item.page_id and not support_request.support_page_id:
                support_request.support_page_id = support_request.item.page_id
            if support_request.item.category_id and not support_request.support_category_id:
                support_request.support_category_id = support_request.item.category_id
            super_category_id = getattr(getattr(support_request.item, 'category', None), 'super_category_id', None)
            if super_category_id and not support_request.support_super_category_id:
                support_request.support_super_category_id = super_category_id
        elif support_request.support_category_id and not support_request.support_super_category_id:
            super_category_id = getattr(support_request.support_category, 'super_category_id', None)
            if super_category_id:
                support_request.support_super_category_id = super_category_id
        support_request.save(update_fields=['support_page', 'support_category', 'support_super_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0004_supportrequest_source_flow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('source_system', models.CharField(blank=True, max_length=120)),
                ('source_flow', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['source_system', 'source_flow', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='requester_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='support_super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='support_center.supportsupercategory'),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='support_center.supportpage'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='support_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='support_center.supportpage'),
        ),
        migrations.RunPython(backfill_support_pages, migrations.RunPython.noop),
    ]
