# Generated by Django 4.2.29 on 2026-04-13 12:00

import uuid

from django.db import migrations, models


def populate_queue_ticket_numbers(apps, schema_editor):
    SupportRequest = apps.get_model("support_center", "SupportRequest")
    for support_request in SupportRequest.objects.filter(queue_ticket_number__isnull=True):
        while True:
            queue_ticket_number = f"PMQ-{uuid.uuid4().hex[:8].upper()}"
            if not SupportRequest.objects.filter(queue_ticket_number=queue_ticket_number).exists():
                support_request.queue_ticket_number = queue_ticket_number
                support_request.save(update_fields=["queue_ticket_number"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("support_center", "0005_supportpage_supportrequest_requester_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="device",
            field=models.CharField(blank=True, choices=[("phone", "Phone"), ("pc", "PC"), ("tablet", "Tablet")], max_length=16),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="device_type",
            field=models.CharField(blank=True, choices=[("android", "Android"), ("ios", "iOS")], max_length=16),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="is_escalated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="queue_ticket_number",
            field=models.CharField(blank=True, editable=False, max_length=24, null=True),
        ),
        migrations.RunPython(populate_queue_ticket_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="supportrequest",
            name="queue_ticket_number",
            field=models.CharField(blank=True, editable=False, max_length=24, unique=True),
        ),
        migrations.AlterModelOptions(
            name="supportrequest",
            options={"ordering": ["-is_escalated", "-created_at"]},
        ),
    ]
