# Generated by Django 4.2.29 on 2026-04-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0006_supportrequest_queue_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportitem',
            name='is_visible_to_publishers',
            field=models.BooleanField(default=False),
        ),
    ]
