# Generated by Django 4.2.29 on 2026-04-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0008_supportrequest_origin_channel_and_supportwidgetevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportitem',
            name='is_visible_to_experts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='is_visible_to_students',
            field=models.BooleanField(default=False),
        ),
    ]
