# Generated by Django 4.2.29 on 2026-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0010_supportwidgetmetricreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='whatsapp_channel',
            field=models.CharField(blank=True, choices=[('rfa', 'RFA'), ('sapa', 'SAPA')], max_length=32),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='origin_channel',
            field=models.CharField(choices=[('direct', 'Direct'), ('assistant', 'Assistant'), ('widget', 'Widget'), ('whatsapp_channel', 'WhatsApp Channel')], default='direct', max_length=24),
        ),
    ]
