# Generated by Django 4.2.29 on 2026-05-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_center', '0011_supportrequest_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='moderator_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='whatsapp_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='whatsapp_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_whatsapp_channel_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
