# Generated by Django 4.2.29 on 2026-05-26 13:33

import apps.support_center.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_center', '0012_supportrequest_moderator_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.support_center.models.support_request_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'svg', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='support_center.supportrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
