# Generated by Django 4.2.29 on 2026-03-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='planning', max_length=16)),
                ('geography', models.CharField(default='India', max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('has_in_clinic', models.BooleanField(default=True)),
                ('has_red_flag_alerts', models.BooleanField(default=True)),
                ('has_patient_education', models.BooleanField(default=True)),
                ('sponsor_banner_url', models.URLField(blank=True)),
                ('support_contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('clinic_code', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_onboarded', models.BooleanField(default=True)),
                ('is_growth_clinic_member', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='campaigns.clinic')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geography', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'geography')},
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='campaigns.clinicgroup'),
        ),
        migrations.CreateModel(
            name='CampaignClinicEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('in_clinic', 'In-clinic'), ('red_flag_alert', 'Red flag alert'), ('patient_education', 'Patient education')], max_length=24)),
                ('enrolled_on', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_enrollments', to='campaigns.campaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='campaigns.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='campaigns.doctor')),
                ('field_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campaign__name', 'clinic__name', 'doctor__full_name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignFieldRepAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rep_assignments', to='campaigns.campaign')),
                ('field_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campaign__name', 'field_rep__email'],
                'unique_together': {('campaign', 'field_rep')},
            },
        ),
    ]
